# Generated by Django 4.1.3 on 2023-04-29 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
